{% set version = "3.0.0.dev20250219+46a22d3f" %}

package:
  name: sapien
  version: {{ version }}

source:
  git_url: git@git.sudoai.co:xiao/sapien-public.git
  git_rev: 46a22d3f711fb1013efe3fc8dc40a05e2419ed7a

requirements:
  host:
    - python