{% set version = "0.2.2" %}

package:
  name: fast_kinematics
  version: {{ version }}

build:
  number: 1

source:
  git_url: https://github.com/Lexseal/fast_kinematics.git
  git_rev: main

requirements:
  build:
    - cmake 3.31.4
  host:
    - python
    - numpy 1.23.3
    - pytorch 2.6.0