{% set version = "2.6.0" %}

package:
  name: torch
  version: {{ version }}

build:
  number: 3

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: v{{ version }}

requirements:
  build:
    - cmake 3.31.4
  host:
    - python
    - numpy 1.23.3