{% set version = "2.6.0" %}

package:
  name: torch
  version: {{ version }}

build:
  number: 3

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: v{{ version }}

requirements:
  build:
    - cmake 3.31.4
    # - typing-extensions 3.10.0.0
    - numpy 1.26.2
  host:
    - python
    # - chaquopy-openblas 0.2.20
    # - numpy 1.26.2
    # - pyyaml 6.0.2
