{% set version = "2.6.0" %}

package:
  name: torch
  version: {{ version }}

build:
  number: 3

source:
  git_url: https://github.com/comoco-xiao/pytorch.git
  git_rev: 8ff72c0c47829088d1025ae658452766a24858ee

requirements:
  build:
    - cmake 3.31.4
    # - typing-extensions 3.10.0.0
  host:
    - python
    # - chaquopy-openblas 0.2.20
    # - numpy 1.26.2
    # - pyyaml 6.0.2
