{% set version = "1.0.2" %}

package:
  name: console_bridge
  version: {{ version }}

build:
  number: 1

source:
  git_url: https://github.com/comoco-xiao/console_bridge.git
  git_rev: master

requirements:
  build:
    - cmake 3.31.4
  host:
    - python