{% set version = "2.7.1" %}

package:
  name: nlopt
  version: {{ version }}

build:
  number: 2

source:
  git_url: https://github.com/DanielBok/nlopt-python.git
  git_rev: "2.7.1.2"

requirements:
  build:
    - cmake 3.31.4
  host:
    - python
    - numpy 1.23.3