{% set version = "3.1.1" %}

package:
  name: urdfdom
  version: {{ version }}

build:
  number: 2

source:
  git_url: https://github.com/comoco-xiao/urdfdom.git
  git_rev: android

requirements:
  build:
    - cmake 3.31.4
  host:
    - python
    - urdfdom_headers 1.0.5
    - console_bridge 1.0.2