{% set version = "3.10.3" %}

package:
  name: eigenpy
  version: {{ version }}

build:
  number: 2

source:
  git_url: https://github.com/comoco-xiao/eigenpy.git
  git_rev: master

requirements:
  build:
    - cmake 3.31.4
  host:
    - python
    - numpy 1.23.3
    - scipy 1.8.1