{% set version = "0.0.1" %}

package:
  name: boostpy
  version: {{ version }}

build:
  number: 1

source:
  git_url: https://github.com/comoco-xiao/boostpy.git
  git_rev: main

requirements:
  build:
    - cmake 3.31.4
  host:
    - python