{% set version = "0.7.4" %}

package:
  name: pytorch-kinematics
  version: {{ version }}

source:
  git_url: https://github.com/UM-ARM-Lab/pytorch_kinematics.git
  git_rev: v{{ version }}

requirements:
  host:
    - python