{% set version = "1.0.5" %}

package:
  name: urdfdom_headers
  version: {{ version }}

build:
  number: 3

source:
  git_url: https://github.com/comoco-xiao/urdfdom_headers.git
  git_rev: master

requirements:
  build:
    - cmake 3.31.4
  host:
    - python