# package:
#   name: h5py
#   version: "2.10.0"

# build:
#   number: 1

# requirements:
#   build:
#     - cython 0.29.14
#     - pkgconfig 1.3.1
#   host:
#     - chaquopy-hdf5 1.10.2
#     - numpy 1.17.4

{% set version = "3.13.0" %}

package:
  name: h5py
  version: {{ version }}

source:
  git_url: https://github.com/h5py/h5py.git
  git_rev: {{ version }}

build:
  number: 1

requirements:
  build:
    - cython 0.29.31
    - pkgconfig 1.3.1
  host:
    - chaquopy-hdf5 1.10.2
    # - numpy 1.17.4
    - numpy 1.23.3