{% set version = "3.4.0" %}

package:
  name: pinocchio
  version: {{ version }}

build:
  number: 2

source:
  git_url: https://github.com/comoco-xiao/pinocchio.git
  git_rev: master

requirements:
  build:
    - cmake 3.31.4
  host:
    - python
    - numpy 1.23.3
    - eigenpy 3.10.3
    - urdfdom_headers 1.0.5
    - console_bridge 1.0.2
    - urdfdom 3.1.1